server:
  port: 8080
  tomcat:
    threads:
      max: 200

spring:
  datasource:
    #配置h2数据库的连接地址
    # Embedded 嵌入式
    # Remote (client/server) 远程连接
    # In-Memory 内存
    url: jdbc:h2:mem:test
    #配置JDBC Driver
    driver-class-name: org.h2.Driver
    #配置数据库用户名
    username: root
    #配置数据库密码
    password: 123456
  h2:
    console:
      #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      enabled: true
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。默认为/h2-console
      path: /h2
      # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      settings:
        web-allow-others: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

redisQueue:
  name: redis:queue