apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
  labels:
    app: spring-boot-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-kubernetes
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
    spec:
      containers:
        - name: spring-boot-kubernetes
          image: spring-boot-kubernetes:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080