apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kubernetes-nodeport
spec:
  selector:
    app: spring-boot-kubernetes
  ports:
    - name: http
      port: 9090 # 暴露出来访问的端口
      protocol: TCP
      targetPort: 8080 # 目标端口
  type: NodePort